#!/usr/bin/env bash

exit_with_usage() {
  echo "Usage: umagick SCRIPT [ARGS...]"
  echo
  echo "  SCRIPT   Path to the ImageMagick script file."
  echo "  ARGS     key=value pairs to pass to the script."
  exit
}

export_vars() {
  for var in "$@"; do
    export "${var?}"
  done
}

create_tmp_script() {
  tmp_script=$(mktemp)
  envsubst < "$original_script" > "$tmp_script"
}

run_script() {
  create_tmp_script
  magick -script "$tmp_script" 
}

cleanup() {
  rm "$tmp_script"
}

run() {
  declare -g original_script
  declare -g tmp_script
  original_script="$1"
  shift

  export_vars "$@"

  run_script
  cleanup
}

main() {
  [[ $# -lt 1 || "$1" == "--help" || "$1" == "-h" ]] && exit_with_usage

  run "$@"
}

main "$@"
