name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Add current directory to path
      run: echo "$PWD" >> $GITHUB_PATH
    - name: Install ImageMagick
      # https://github.com/SoftCreatR/imei/
      run: |
        t=$(mktemp) && \
        wget 'https://dist.1-2.dev/imei.sh' -qO "$t" && \
        bash "$t" && \
        rm "$t"
    - name: Run shellcheck tests
      run: shellcheck umagick
    - name: Run approval tests
      run: test/approve
