name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Add current directory to path
      run: echo "$PWD" >> $GITHUB_PATH
    - name: Run shellcheck tests
      run: shellcheck umagick
    - name: Run approval tests
      run: test/approve
